# project definitions
project: doc
audience: all
product: all
platform: all
version: all
destination: _site
topnav_title: Stanza
homepage_title: Stanza - A Python NLP Library for Many Human Languages
site_title: Stanza
#disqus_shortname: idrbwjekyll
google_analytics: UA-133356038-1

# variables

sidebar_tagline: <img src="images/stanza.png" style="width:70%; margin-bottom:5px" />
sidebar_version: <img alt="PyPI Version" src="https://img.shields.io/pypi/v/stanza.svg?colorB=bc4545" /> <img alt="Conda Versions" src="https://img.shields.io/conda/vn/stanfordnlp/stanza?color=blue&label=conda" /> <img alt="Python Versions" src="https://img.shields.io/pypi/pyversions/stanza.svg?colorB=bc4545" />
project_file_name: doc
company_name: Stanford NLP

port: 4001

exclude:
  - configs/
  - _site
  - di_multi*

include:
  - _pages

# avoid https mixed content?
url: https://stanfordnlp.github.io/stanza
# same for all
host: 127.0.0.1
sidebar_accordion: true
markdown: kramdown
print: false
theme_file: theme-cardinal.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: rouge

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

relative_links:
  enabled:     true
  collections: false

plugins:
  - jekyll-relative-links
